scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: 'TelemetryHungry'
    scrape_interval: 5s
    static_configs:
    - targets: ['otel-collector:8888']
    - targets: ['otel-collector:8889']
    - targets: ['otel-collector:9184']
